FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive 
# install build toolchain
RUN apt-get update && apt-get install -y git build-essential qtcreator qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libusb-1.0-0-dev libhidapi-dev pkgconf libmbedtls-dev qttools5-dev-tools

