FROM ubuntu:22.04


# install build toolchain
RUN apt-get update && apt-get install -y build-essential vim git gettext flex bison libtool autoconf automake pkg-config libpcap-dev libjson-c-dev libnuma-dev libpcre2-dev libmaxminddb-dev librrd-dev

